FROM php:7.2-fpm
COPY php.ini /usr/local/etc/php/
#RUN buildの際に実行されるコマンド
RUN apt update
RUN apt install -y default-mysql-client
RUN docker-php-ext-install pdo_mysql
#mysql-clientをphpコンテナにインストール、pdo自体とpdoのmysqlドライバーをインストール
